import { narration } from "./narration.js";

/**
 * Deterministic product walkthrough. Times are milliseconds from demo start.
 * Total ~4:30. First 20s is the hook.
 *
 * Scene fields: duration, narration, speechMs, targetElement, orbPosition,
 * action, transition, highlight, waitAfterSpeech, plus stage/beats for the UI.
 * Narration is a speech bubble only — no audio files.
 */
export const DEMO_TOTAL_MS = 270_000;

export const scenes = [
  {
    id: "hook",
    chapter: "hook",
    start: 0,
    duration: 20_000,
    stage: "hero",
    narration: narration.hook,
    speechMs: 8_500,
    targetElement: "hero-get-started",
    orbPosition: "br",
    action: { type: "appear" },
    transition: "fade",
    highlight: { target: "hero-get-started", duration: 5200, pointer: true },
    waitAfterSpeech: 1200,
    highlightAt: 9000,
  },
  {
    id: "problem",
    chapter: "problem",
    start: 20_000,
    duration: 25_000,
    stage: "problem",
    narration: narration.problem,
    speechMs: 8_200,
    targetElement: "compare-without",
    orbPosition: "br",
    action: { type: "navigate", to: "problem" },
    transition: "fade",
    highlight: { target: "compare-without", duration: 7000, pointer: true },
    waitAfterSpeech: 1000,
    highlightAt: 1500,
    beats: [{ at: 14_000, highlight: { target: "compare-with", duration: 8000, pointer: true } }],
  },
  {
    id: "how-1",
    chapter: "how",
    start: 45_000,
    duration: 13_000,
    stage: "how",
    narration: narration.how1,
    speechMs: 6_200,
    targetElement: "how-1",
    orbPosition: "br",
    action: { type: "navigate", to: "how" },
    transition: "fade",
    highlight: { target: "how-1", duration: 9000, pointer: true },
    waitAfterSpeech: 800,
    highlightAt: 400,
  },
  {
    id: "how-2",
    chapter: "how",
    start: 58_000,
    duration: 12_000,
    stage: "how",
    narration: narration.how2,
    speechMs: 6_000,
    targetElement: "how-2",
    orbPosition: "br",
    action: null,
    transition: "none",
    highlight: { target: "how-2", duration: 8500, pointer: true },
    waitAfterSpeech: 700,
    highlightAt: 300,
  },
  {
    id: "how-3",
    chapter: "how",
    start: 70_000,
    duration: 12_000,
    stage: "how",
    narration: narration.how3,
    speechMs: 6_200,
    targetElement: "how-3",
    orbPosition: "br",
    action: null,
    transition: "none",
    highlight: { target: "how-3", duration: 8500, pointer: true },
    waitAfterSpeech: 700,
    highlightAt: 300,
  },
  {
    id: "how-4",
    chapter: "how",
    start: 82_000,
    duration: 8_000,
    stage: "how",
    narration: narration.how4,
    speechMs: 5_400,
    targetElement: "how-4",
    orbPosition: "bl",
    action: null,
    transition: "none",
    highlight: { target: "how-4", duration: 6000, pointer: true },
    waitAfterSpeech: 500,
    highlightAt: 200,
  },
  {
    id: "demo-customers",
    chapter: "main",
    start: 90_000,
    duration: 12_000,
    stage: "customers",
    narration: narration.customers,
    speechMs: 6_400,
    targetElement: "add-customer",
    orbPosition: "br",
    action: { type: "navigate", to: "customers" },
    transition: "fade",
    highlight: { target: "add-customer", duration: 7000, pointer: true },
    waitAfterSpeech: 800,
    highlightAt: 1600,
  },
  {
    id: "demo-job",
    chapter: "main",
    start: 102_000,
    duration: 13_000,
    stage: "jobs",
    narration: narration.job,
    speechMs: 4_800,
    targetElement: "add-job",
    orbPosition: "br",
    action: { type: "fill", form: "job" },
    transition: "fade",
    highlight: { target: "add-job", duration: 3500, pointer: true },
    waitAfterSpeech: 600,
    highlightAt: 400,
    beats: [
      { at: 2800, ui: { jobModal: true } },
      { at: 4800, ui: { jobFilled: true } },
      { at: 7800, ui: { jobModal: false, jobCompleted: true }, highlight: { target: "demo-job-row", duration: 4000, pointer: true } },
    ],
  },
  {
    id: "demo-process",
    chapter: "main",
    start: 115_000,
    duration: 15_000,
    stage: "requests",
    variant: "waiting",
    narration: narration.processing,
    speechMs: 6_000,
    targetElement: "demo-request-row",
    orbPosition: "br",
    action: { type: "navigate", to: "requests" },
    transition: "fade",
    highlight: { target: "demo-request-row", duration: 9000, pointer: true },
    waitAfterSpeech: 800,
    highlightAt: 1200,
  },
  {
    id: "demo-result",
    chapter: "main",
    start: 130_000,
    duration: 12_000,
    stage: "requests",
    variant: "sent",
    narration: narration.result,
    speechMs: 6_200,
    targetElement: "demo-request-row",
    orbPosition: "br",
    action: null,
    transition: "none",
    highlight: { target: "demo-request-sent", duration: 8000, pointer: true },
    waitAfterSpeech: 700,
    highlightAt: 800,
  },
  {
    id: "demo-benefit",
    chapter: "main",
    start: 142_000,
    duration: 8_000,
    stage: "dashboard",
    narration: narration.benefit,
    speechMs: 5_600,
    targetElement: "dashboard-stats",
    orbPosition: "br",
    action: { type: "navigate", to: "dashboard" },
    transition: "fade",
    highlight: { target: "dashboard-stats", duration: 5500, pointer: true },
    waitAfterSpeech: 400,
    highlightAt: 500,
  },
  {
    id: "ai-open",
    chapter: "assistant",
    start: 150_000,
    duration: 12_000,
    stage: "dashboard",
    narration: narration.aiOpen,
    speechMs: 5_200,
    targetElement: "ai-orb-button",
    orbPosition: "chat",
    action: { type: "click", target: "orb" },
    transition: "none",
    highlight: { target: "ai-orb-button", duration: 4000, pointer: true },
    waitAfterSpeech: 600,
    highlightAt: 400,
    beats: [{ at: 7000, chat: "open" }],
  },
  {
    id: "ai-ask",
    chapter: "assistant",
    start: 162_000,
    duration: 18_000,
    stage: "dashboard",
    narration: narration.aiReply,
    speechMs: 7_200,
    targetElement: "add-job",
    orbPosition: "chat",
    action: { type: "message", role: "user", text: narration.aiAsk },
    transition: "none",
    highlight: { target: "new-job", duration: 8000, pointer: true },
    waitAfterSpeech: 800,
    highlightAt: 8200,
    beats: [
      { at: 400, chat: "open", message: { role: "user", text: narration.aiAsk } },
      { at: 1600, state: "thinking" },
      { at: 3200, message: { role: "assistant", text: narration.aiReply }, state: "speaking" },
    ],
  },
  {
    id: "ai-highlight",
    chapter: "assistant",
    start: 180_000,
    duration: 15_000,
    stage: "how",
    narration: "",
    speechMs: 0,
    targetElement: "how-3",
    orbPosition: "bl",
    action: { type: "navigate", to: "how" },
    transition: "fade",
    highlight: { target: "how-3", duration: 10_000, pointer: true },
    waitAfterSpeech: 0,
    highlightAt: 600,
    beats: [{ at: 200, chat: "close" }],
  },
  {
    id: "benefits",
    chapter: "benefits",
    start: 195_000,
    duration: 45_000,
    stage: "benefits",
    narration: narration.benefits,
    speechMs: 6_800,
    targetElement: "features",
    orbPosition: "br",
    action: { type: "navigate", to: "benefits" },
    transition: "fade",
    highlight: { target: "demo-benefit-auto", duration: 8000, pointer: true },
    waitAfterSpeech: 1000,
    highlightAt: 1200,
    beats: [
      { at: 12_000, highlight: { target: "demo-benefit-simple", duration: 9000, pointer: true } },
      { at: 24_000, highlight: { target: "demo-benefit-status", duration: 9000, pointer: true } },
      { at: 34_000, highlight: { target: "demo-benefit-guide", duration: 8000, pointer: true } },
    ],
  },
  {
    id: "cta",
    chapter: "cta",
    start: 240_000,
    duration: 30_000,
    stage: "cta",
    narration: narration.cta,
    speechMs: 6_000,
    targetElement: "closing-cta",
    orbPosition: "br",
    action: { type: "navigate", to: "cta" },
    transition: "fade",
    highlight: { target: "closing-cta", duration: 16_000, pointer: true },
    waitAfterSpeech: 1200,
    highlightAt: 1500,
  },
];

export function sceneAt(elapsed) {
  for (let i = scenes.length - 1; i >= 0; i -= 1) {
    if (elapsed >= scenes[i].start) return scenes[i];
  }
  return scenes[0];
}
